name: Restful-Booker Environment
values:
  - key: baseUrl
    value: 'https://restful-booker.herokuapp.com'
  - key: adminUsername
    value: admin
  - key: adminPassword
    value: password123
  - key: token
    value: ''
  - key: bookingId
    value: ''
  - key: testFirstname
    value: John
  - key: testLastname
    value: Doe
  - key: testCheckin
    value: '2026-01-01'
  - key: testCheckout
    value: '2026-01-10'
  - key: testTotalprice
    value: '150'
  - key: testAdditionalneeds
    value: Breakfast
  - key: invalidBookingId
    value: '999999'
  - key: futureDate
    value: '2027-12-31'
  - key: pastDate
    value: '2020-01-01'
  - key: updatedFirstname
    value: James
  - key: updatedLastname
    value: Brown
  - key: updatedTotalprice
    value: '200'
  - key: xmlCheckin
    value: '2026-01-01'
  - key: xmlCheckout
    value: '2026-01-05'
  - key: xmlFirstname
    value: Jim
  - key: xmlLastname
    value: Brown
  - key: xmlTotalprice
    value: '111'
  - key: xmlAdditionalneeds
    value: Breakfast
  - key: newBookingId
    value: ''
color: 240
